FICTIONAL_PHYSICIANS = [
    {
        "name": "Dr. Arjun Rao",
        "specialty": "Cardiology",
        "sub_specialty": "Interventional Cardiology",
        "experience_years": 14,
        "rating": 4.8,
        "review_count": 326,
        "city": "Nellore",
        "state": "Andhra Pradesh",
        "country": "India",
        "distance_km": 3.2,
        "available": True,
    },
    {
        "name": "Dr. Meera Krishnan",
        "specialty": "Cardiology",
        "sub_specialty": "Echocardiography",
        "experience_years": 11,
        "rating": 4.7,
        "review_count": 241,
        "city": "Nellore",
        "state": "Andhra Pradesh",
        "country": "India",
        "distance_km": 5.6,
        "available": True,
    },
    {
        "name": "Dr. Vikram Reddy",
        "specialty": "Cardiology",
        "sub_specialty": "Clinical Cardiology",
        "experience_years": 18,
        "rating": 4.6,
        "review_count": 418,
        "city": "Nellore",
        "state": "Andhra Pradesh",
        "country": "India",
        "distance_km": 8.4,
        "available": False,
    },
    {
        "name": "Dr. Priya Sharma",
        "specialty": "Nephrology",
        "sub_specialty": "Clinical Nephrology",
        "experience_years": 12,
        "rating": 4.8,
        "review_count": 287,
        "city": "Nellore",
        "state": "Andhra Pradesh",
        "country": "India",
        "distance_km": 4.1,
        "available": True,
    },
    {
        "name": "Dr. Kiran Kumar",
        "specialty": "Gastroenterology",
        "sub_specialty": "Interventional Gastroenterology",
        "experience_years": 15,
        "rating": 4.7,
        "review_count": 301,
        "city": "Nellore",
        "state": "Andhra Pradesh",
        "country": "India",
        "distance_km": 6.2,
        "available": True,
    },
    {
        "name": "Dr. Ananya Menon",
        "specialty": "Neurology",
        "sub_specialty": "Clinical Neurology",
        "experience_years": 13,
        "rating": 4.8,
        "review_count": 275,
        "city": "Nellore",
        "state": "Andhra Pradesh",
        "country": "India",
        "distance_km": 7.0,
        "available": True,
    },
    {
        "name": "Dr. Rahul Verma",
        "specialty": "Orthopedics",
        "sub_specialty": "Joint Replacement",
        "experience_years": 16,
        "rating": 4.6,
        "review_count": 355,
        "city": "Nellore",
        "state": "Andhra Pradesh",
        "country": "India",
        "distance_km": 5.0,
        "available": True,
    },
    {
        "name": "Dr. Sneha Patel",
        "specialty": "Ophthalmology",
        "sub_specialty": "Retina",
        "experience_years": 10,
        "rating": 4.7,
        "review_count": 219,
        "city": "Nellore",
        "state": "Andhra Pradesh",
        "country": "India",
        "distance_km": 9.1,
        "available": True,
    },
]