"""create medical reports table

Revision ID: 364d077533b3
Revises: 292b66660644
Create Date: 2026-09-19 07:21:25.544662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '364d077533b3'
down_revision: Union[str, Sequence[str], None] = '292b66660644'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=True),
    sa.Column('primary_specialty', sa.String(length=100), nullable=True),
    sa.Column('routing_score_percentage', sa.Float(), nullable=True),
    sa.Column('confidence_level', sa.String(length=30), nullable=True),
    sa.Column('specialties', sa.JSON(), nullable=True),
    sa.Column('findings', sa.JSON(), nullable=True),
    sa.Column('measurements', sa.JSON(), nullable=True),
    sa.Column('physicians', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_medical_reports_user_created', 'medical_reports', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_medical_reports_user_created', table_name='medical_reports')
    op.drop_table('medical_reports')
    # ### end Alembic commands ###
