import {
  Activity,
  ArrowLeft,
  ArrowRight,
  ClipboardList,
  FileText,
  History,
  Home,
  Image,
  LogOut,
  MapPin,
  ShieldCheck,
  Stethoscope,
} from 'lucide-react'
import { Link } from 'react-router-dom'

import RiskNotice from '../components/RiskNotice'
import { useAuth } from '../context/useAuth.js'

const primaryTools = [
  {
    icon: Stethoscope,
    number: '01',
    eyebrow: 'Symptom Analysis',
    title: 'Analyze Symptoms',
    description:
      'Describe your symptoms in natural language and review ranked model-generated possibilities.',
    href: '/diagnosis',
    buttonText: 'Start Symptom Analysis',
    iconClass: 'bg-[#eaf1ff] text-[#2563eb]',
    buttonClass: 'bg-[#2563eb] hover:bg-[#1d4ed8]',
  },
  {
    icon: FileText,
    number: '02',
    eyebrow: 'Medical Reports',
    title: 'Analyze a Medical Report',
    description:
      'Upload a supported report and review extracted findings, measurements, and specialty information.',
    href: '/medical-analysis',
    buttonText: 'Upload Medical Report',
    iconClass: 'bg-[#e8f8f5] text-[#0f766e]',
    buttonClass: 'bg-[#0f766e] hover:bg-[#0b625c]',
  },
  {
    icon: Image,
    number: '03',
    eyebrow: 'Chest X-ray',
    title: 'Analyze an X-ray',
    description:
      'Review a bounded model-generated pneumonia-related pattern finding from a chest X-ray.',
    href: '/xray-analysis',
    buttonText: 'Upload Chest X-ray',
    iconClass: 'bg-[#fff3e5] text-[#da7d43]',
    buttonClass: 'bg-[#da7d43] hover:bg-[#c86c35]',
  },
]

const workflow = [
  {
    number: '01',
    title: 'Provide information',
    text: 'Describe symptoms or upload supported medical information.',
  },
  {
    number: '02',
    title: 'Review the model output',
    text: 'Explore the information generated by the relevant SymptomLens model.',
  },
  {
    number: '03',
    title: 'Take the next step',
    text: 'Use the information to prepare for a conversation with a healthcare professional.',
  },
]

export default function Dashboard() {
  const {
    user,
    logout,
  } = useAuth()

  const displayName =
    user?.name ||
    user?.full_name ||
    'there'

  return (
    <div className="min-h-screen bg-[#f4f8f7] text-[#102a2a]">
      {/* HEADER */}
      <header className="sticky top-0 z-30 border-b border-[#dce7e5] bg-white/95 backdrop-blur">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4 lg:px-8">
          <div className="flex items-center gap-4">
            <Link
              to="/"
              className="group inline-flex items-center gap-2 rounded-xl border border-[#ccdcd9] bg-white px-4 py-2.5 text-sm font-bold text-[#284947] shadow-sm transition duration-200 hover:-translate-y-0.5 hover:border-[#173d5a] hover:bg-[#f3f8ff] hover:text-[#173d5a]"
            >
              <ArrowLeft
                size={16}
                className="transition-transform duration-200 group-hover:-translate-x-0.5"
              />
              Home
            </Link>

            <div className="hidden h-7 w-px bg-[#dce7e5] sm:block" />

            <div className="hidden sm:block">
              <p className="text-sm font-bold text-[#173d5a]">
                SymptomLens
              </p>

              <p className="text-[11px] font-medium text-[#80918f]">
                Dashboard
              </p>
            </div>
          </div>

          <div className="flex items-center gap-3">
            <div className="hidden text-right sm:block">
              <p className="text-sm font-bold text-[#284947]">
                {displayName}
              </p>

              <p className="max-w-[220px] truncate text-xs text-[#829290]">
                {user?.email || 'Signed in'}
              </p>
            </div>

            <button
              type="button"
              onClick={logout}
              className="inline-flex items-center gap-2 rounded-xl border border-[#efcfca] bg-white px-4 py-2.5 text-sm font-bold text-[#a84b43] transition duration-200 hover:-translate-y-0.5 hover:border-[#d65b51] hover:bg-[#fff5f3] hover:text-[#8e3029]"
            >
              <LogOut size={16} />

              <span className="hidden sm:inline">
                Log out
              </span>
            </button>
          </div>
        </div>
      </header>

      <main className="mx-auto max-w-7xl px-6 py-10 lg:px-8 lg:py-14">
        {/* BREADCRUMB */}
        <div className="mb-7 flex items-center gap-2 text-sm">
          <Link
            to="/"
            className="font-semibold text-[#6a7f7d] transition hover:text-[#173d5a]"
          >
            Home
          </Link>

          <span className="text-[#afbfbd]">
            /
          </span>

          <span className="font-bold text-[#173d5a]">
            Dashboard
          </span>
        </div>

        {/* WELCOME */}
        <section
          className="overflow-hidden rounded-[2rem] p-7 text-white shadow-[0_24px_70px_rgba(23,61,90,0.14)] sm:p-10"
          style={{
            background:
              'linear-gradient(135deg, #173d5a 0%, #15566b 56%, #0f766e 100%)',
          }}
        >
          <div className="flex flex-col gap-8 lg:flex-row lg:items-center lg:justify-between">
            <div>
              <span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-xs font-bold uppercase tracking-[0.15em] text-[#cfe8e3] ring-1 ring-white/10">
                <Activity size={14} />
                Personal Workspace
              </span>

              <h1 className="heading mt-4 text-4xl font-bold tracking-[-0.04em] sm:text-5xl">
                Welcome back,
                <span className="block text-[#a6e5d9]">
                  {displayName}.
                </span>
              </h1>

              <p className="mt-4 max-w-2xl leading-7 text-[#d7ece8]">
                Choose an analysis, review your saved records,
                or find a healthcare professional through an
                external provider directory.
              </p>
            </div>

            <div className="flex shrink-0 items-center gap-3 rounded-2xl bg-white/10 p-4 ring-1 ring-white/10">
              <div className="grid h-11 w-11 place-items-center rounded-xl bg-white/10">
                <ShieldCheck size={21} />
              </div>

              <div>
                <p className="text-xs font-bold uppercase tracking-[0.14em] text-[#b8d9d4]">
                  Account
                </p>

                <p className="mt-1 text-sm font-semibold text-white">
                  Signed in
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* PRIMARY TOOLS */}
        <section className="mt-10">
          <div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between">
            <div>
              <p className="text-xs font-bold uppercase tracking-[0.16em] text-[#e8793f]">
                Your tools
              </p>

              <h2 className="heading mt-2 text-3xl font-bold text-[#102a2a]">
                Start an analysis
              </h2>
            </div>

            <p className="max-w-xl text-sm leading-6 text-[#71847a] sm:text-right">
              Choose the type of health information you want
              to explore.
            </p>
          </div>

          <div className="mt-6 grid gap-5 lg:grid-cols-3">
            {primaryTools.map(
              ({
                icon,
                number,
                eyebrow,
                title,
                description,
                href,
                buttonText,
                iconClass,
                buttonClass,
              }) => (
                <DashboardCard
                  key={number}
                  icon={icon}
                  badge={number}
                  eyebrow={eyebrow}
                  title={title}
                  description={description}
                  href={href}
                  buttonText={buttonText}
                  iconClass={iconClass}
                  buttonClass={buttonClass}
                />
              ),
            )}
          </div>
        </section>

        {/* HISTORY + PROFESSIONAL */}
        <section className="mt-6 grid gap-5 lg:grid-cols-2">
          <article className="rounded-[2rem] border border-[#dce7e5] bg-white p-7 shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-xl sm:p-8">
            <div className="flex items-start justify-between gap-4">
              <div className="grid h-12 w-12 place-items-center rounded-2xl bg-[#e9f8f2] text-[#07856b]">
                <History size={23} />
              </div>

              <span className="rounded-full bg-[#edf8f4] px-3 py-1.5 text-xs font-bold tracking-[0.12em] text-[#07856b]">
                SAVED RECORDS
              </span>
            </div>

            <h2 className="heading mt-7 text-2xl font-bold text-[#102a2a] sm:text-3xl">
              My History
            </h2>

            <p className="mt-3 max-w-xl leading-7 text-[#58716e]">
              Open your saved symptom analyses and review
              the records attached to your account.
            </p>

            <Link
              to="/history"
              className="mt-7 inline-flex min-h-[50px] items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-[#079b7b] to-[#0f766e] px-6 py-3 text-sm font-bold text-white shadow-md shadow-[#0f766e]/20 transition duration-200 hover:-translate-y-0.5 hover:from-[#067e65] hover:to-[#0b625c] hover:shadow-lg active:translate-y-0"
            >
              <History size={18} />
              Open My History
              <ArrowRight size={17} />
            </Link>
          </article>

          <article className="rounded-[2rem] border border-[#dce7e5] bg-white p-7 shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-xl sm:p-8">
            <div className="flex items-start justify-between gap-4">
              <div className="grid h-12 w-12 place-items-center rounded-2xl bg-[#edf3ff] text-[#2563eb]">
                <MapPin size={23} />
              </div>

              <span className="rounded-full bg-[#edf3ff] px-3 py-1.5 text-xs font-bold tracking-[0.12em] text-[#2563eb]">
                PROFESSIONAL CARE
              </span>
            </div>

            <h2 className="heading mt-7 text-2xl font-bold text-[#102a2a] sm:text-3xl">
              Find a Professional
            </h2>

            <p className="mt-3 max-w-xl leading-7 text-[#58716e]">
              Explore official healthcare provider directories
              to find doctors, current profiles, and appointment
              options.
            </p>

            <Link
              to="/medical-analysis"
              className="mt-7 inline-flex min-h-[50px] items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-[#2563eb] to-[#1d4ed8] px-6 py-3 text-sm font-bold text-white shadow-md shadow-[#2563eb]/20 transition duration-200 hover:-translate-y-0.5 hover:shadow-lg active:translate-y-0"
            >
              <Stethoscope size={18} />
              Find a Professional
              <ArrowRight size={17} />
            </Link>
          </article>
        </section>

        {/* HOW IT WORKS */}
        <section className="mt-10">
          <div className="rounded-[2rem] border border-[#dce7e5] bg-white p-7 shadow-sm sm:p-9">
            <div className="max-w-2xl">
              <p className="text-xs font-bold uppercase tracking-[0.16em] text-[#e8793f]">
                How SymptomLens works
              </p>

              <h2 className="heading mt-2 text-3xl font-bold text-[#102a2a]">
                From information to your next conversation.
              </h2>

              <p className="mt-3 leading-7 text-[#58716e]">
                SymptomLens organizes health information and
                presents model-generated outputs so you can
                better understand what to discuss with a
                healthcare professional.
              </p>
            </div>

            <div className="mt-8 grid gap-4 md:grid-cols-3">
              {workflow.map(
                ({
                  number,
                  title,
                  text,
                }) => (
                  <div
                    key={number}
                    className="rounded-2xl border border-[#e0e9e6] bg-[#f8fbfa] p-5"
                  >
                    <span className="text-sm font-black text-[#da7d43]">
                      {number}
                    </span>

                    <h3 className="mt-4 font-bold text-[#173d32]">
                      {title}
                    </h3>

                    <p className="mt-2 text-sm leading-6 text-[#687c77]">
                      {text}
                    </p>
                  </div>
                ),
              )}
            </div>
          </div>
        </section>

        {/* SAFETY */}
        <section className="mt-8">
          <RiskNotice />
        </section>

        {/* ACCOUNT / HOME */}
        <section className="mt-8 grid gap-5 md:grid-cols-2">
          <div className="rounded-[2rem] border border-[#dce7e5] bg-white p-6 shadow-sm">
            <div className="flex items-center gap-3">
              <div className="grid h-10 w-10 place-items-center rounded-xl bg-[#e8f8f5] text-[#0f766e]">
                <ShieldCheck size={19} />
              </div>

              <div>
                <p className="text-xs font-bold uppercase tracking-[0.14em] text-[#829290]">
                  Account
                </p>

                <p className="mt-1 text-sm font-bold text-[#102a2a]">
                  {user?.email || 'Authenticated user'}
                </p>
              </div>
            </div>

            <p className="mt-4 text-sm leading-6 text-[#687c77]">
              Your saved analyses are linked to your signed-in
              SymptomLens account.
            </p>
          </div>

          <div className="rounded-[2rem] border border-[#dce7e5] bg-white p-6 shadow-sm">
            <div className="flex items-center gap-3">
              <div className="grid h-10 w-10 place-items-center rounded-xl bg-[#fff3e6] text-[#da7d43]">
                <Home size={19} />
              </div>

              <div>
                <p className="text-xs font-bold uppercase tracking-[0.14em] text-[#829290]">
                  Navigation
                </p>

                <p className="mt-1 text-sm font-bold text-[#102a2a]">
                  Explore the public homepage
                </p>
              </div>
            </div>

            <Link
              to="/"
              className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-[#da7d43] transition hover:text-[#b95725]"
            >
              Back to Home
              <ArrowRight size={16} />
            </Link>
          </div>
        </section>
      </main>
    </div>
  )
}

function DashboardCard({
  icon: Icon,
  badge,
  eyebrow,
  title,
  description,
  href,
  buttonText,
  iconClass,
  buttonClass,
}) {
  return (
    <article className="group flex h-full flex-col rounded-[2rem] border border-[#dce7e5] bg-white p-7 shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-xl sm:p-8">
      <div className="flex items-start justify-between gap-4">
        <div
          className={`grid h-12 w-12 place-items-center rounded-2xl ${iconClass}`}
        >
          <Icon size={23} />
        </div>

        <span className="rounded-full bg-[#f2f6f5] px-3 py-1.5 text-xs font-bold tracking-[0.12em] text-[#7c8f8d]">
          {badge}
        </span>
      </div>

      <p className="mt-7 text-xs font-bold uppercase tracking-[0.16em] text-[#e8793f]">
        {eyebrow}
      </p>

      <h2 className="heading mt-2 text-2xl font-bold text-[#102a2a] sm:text-3xl">
        {title}
      </h2>

      <p className="mt-3 flex-1 leading-7 text-[#58716e]">
        {description}
      </p>

      <Link
        to={href}
        className={`mt-7 inline-flex min-h-[50px] items-center justify-center gap-2 rounded-xl px-6 py-3 text-sm font-bold text-white shadow-md transition duration-200 hover:-translate-y-0.5 hover:shadow-lg active:translate-y-0 ${buttonClass}`}
      >
        {buttonText}
        <ArrowRight size={17} />
      </Link>
    </article>
  )
}